SPLITS_KEY = "splits"
BACKTRACKS_KEY = "backtracks"
UNIT_CLAUSES_KEY = "unit_clauses"
PURE_LITERALS_KEY = "pure_literals"
HINTS_KEY = "hints"
SPLITS_TO_BACKTRACKS_KEY = "splits_to_backtracks_ratio"

# timer constants
TIMER1_KEY = "timer1"
TIMER2_KEY = "timer2"
TIMER3_KEY = "timer3"
TIMER4_KEY = "timer4"
TIMER5_KEY = "timer5"
TIMER6_KEY = "timer6"
GAMETIME_KEY = "game_time"